### ISSUE TITLE
mpv --idle never ends

### ISSUE THREAD

**Issue by dufferzafar** [donmaiq/unseen-playlistmaker#1]
I am running this on Ubuntu 15.10. I set up my paths in the file & changed the scan line to:

``` lua
local scan = 'find'..search..'-type f -maxdepth 1 -printf "%f\\n"'
```

And then ran `mpv --idle` but it just kept on running...

I know you're probably not on Linux, but if you could guide me towards debugging this problem, it'd be great!

**Comment by jonniek** [comment]
Can you explain a little bit more in detail?
1.Was txtfile created when you ran idle
2.did the terminal print 'playlist-mode activated' when you pressed W in --idle mode.
3.did any files in your media directory start playing?

When you run mpv --idle nothing should happen(apart from creating a .txt file at first time), you need to activate the search with W. If there is no files loaded even though there is files in the directory, then the problem should be in the scan variable. Try optimizing the command in your terminal so that it returns files correctly.

Sorry for late reply.

**Comment by dufferzafar** [comment]
@jonniek I kept fiddling with the script for quite some time, then read the code and figured out that running `mpv --idle` doesn't actually do anything apart from creating the text file. The plugin is working great :) Thanks a lot for this.
